-- CreateTable
CREATE TABLE `Activity` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `mentorName` VARCHAR(191) NOT NULL DEFAULT '',
    `timeText` VARCHAR(191) NOT NULL DEFAULT '',
    `place` VARCHAR(191) NOT NULL DEFAULT '',
    `limit` INTEGER NOT NULL DEFAULT 0,
    `description` VARCHAR(191) NOT NULL DEFAULT '',
    `status` ENUM('DRAFT', 'PUBLISHED', 'OPEN', 'CLOSED', 'FINISHED', 'CANCELED') NOT NULL DEFAULT 'PUBLISHED',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
