-- AlterTable
ALTER TABLE `user` ADD COLUMN `className` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `contact` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `name` VARCHAR(191) NOT NULL DEFAULT '';
