-- AlterTable
ALTER TABLE `activityregistration` ADD COLUMN `reviewNote` VARCHAR(191) NULL DEFAULT '',
    MODIFY `status` ENUM('REGISTERED', 'PENDING_CANCEL', 'CANCELED') NOT NULL DEFAULT 'REGISTERED';
